'use client';

/**
 * Copyright since 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  ArrowLeftRight,
  ArrowRightLeft,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  CheckSquare,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Cog,
  Coins,
  CreditCard,
  Database,
  DoorClosed,
  FileBarChart,
  FileStack,
  FileText,
  Gavel,
  Handshake,
  Hash,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  Link2,
  List,
  Lock,
  Map,
  MessageSquare,
  NotebookPen,
  Package,
  Percent,
  Phone,
  PieChart,
  PiggyBank,
  Receipt,
  RefreshCw,
  Repeat2,
  Scale,
  ScrollText,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Store,
  Table2,
  Terminal,
  Timer,
  TrendingUp,
  Upload,
  User,
  Users,
  UsersRound,
  Wallet,
  Webhook,
  Zap,
  type LucideIcon
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  users: Users,
  user: User,
  'users-round': UsersRound,
  'building-2': Building2,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  'book-open': BookOpen,
  calculator: Calculator,
  building: Building,
  settings: Settings,
  inbox: Inbox,
  search: Search,
  'file-bar-chart': FileBarChart,
  package: Package,
  shield: Shield,
  database: Database,
  cog: Cog,
  list: List,
  coins: Coins,
  'message-square': MessageSquare,
  phone: Phone,
  'arrow-left-right': ArrowLeftRight,
  map: Map,
  'trending-up': TrendingUp,
  terminal: Terminal,
  store: Store,
  'credit-card': CreditCard,
  'key-round': KeyRound,
  shuffle: Shuffle,
  'table-2': Table2,
  'calendar-days': CalendarDays,
  handshake: Handshake,
  upload: Upload,
  calendar: Calendar,
  'code-2': Code2,
  zap: Zap,
  'link-2': Link2,
  cloud: Cloud,
  webhook: Webhook,
  'check-square': CheckSquare,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'sliders-horizontal': SlidersHorizontal,
  hash: Hash,
  info: Info,
  'scroll-text': ScrollText,
  'pie-chart': PieChart,
  percent: Percent,
  layers: Layers,
  receipt: Receipt,
  'alert-triangle': AlertTriangle,
  'refresh-cw': RefreshCw,
  lock: Lock,
  'shield-check': ShieldCheck,
  'badge-check': BadgeCheck,
  'notebook-pen': NotebookPen,
  'repeat-2': Repeat2,
  activity: Activity,
  'arrow-right-left': ArrowRightLeft,
  'door-closed': DoorClosed,
  gavel: Gavel,
  timer: Timer,
  'file-stack': FileStack,
  'file-text': FileText,
  scale: Scale,
  briefcase: Briefcase
};

export function NavIcon({ name, className }: { name?: string; className?: string }) {
  const Icon = name ? ICONS[name] : undefined;
  if (!Icon) {
    return <span className={className} aria-hidden />;
  }
  return <Icon className={className} aria-hidden />;
}
